### ISSUE TITLE
I have no idea how to GITHUB

### ISSUE THREAD

**Issue by CORElysta** [MrMusovic/PokemonProject#2]
were we supposed to know how to do this because I had an account but have no recollection of creating one and haven't used it in this class yet

**Comment by MrMusovic** [comment]
Github is a version control system. So that if there's an issue we can roll back to a functioning version. 
Collaboration + version control = no loss of hours. 

**Step 0**: Download git: https://git-scm.com/downloads

**Step 1**: Go to GitHub and create an account (use your school email). Keep your personal one separate for future use. 

**Step 2**: Go to:
https://help.github.com/en/github/getting-started-with-github/set-up-git

This guide states:
    Download and install the latest version of Git (you've done this)
    Set your username in Git by:
    Open Git in VS Code .
    Set your commit email address in Git -do this.

**Step 3**
Go to VS Code
Open a new project folder that our lovely  project will be sucked to (8DT oneNote folder is fine). 
Press Ctrl + ~ (will bring up terminal)
Click on the 1: Powershell and then change default. 
From the new drop down click bash. 

Select the plus sign on the right hand side and select bash from the drop down. 
Yes!

**Step 4:** Setup your Github Username 
Now it is typing time. 
Set a Git username:
    $ git config --global user.name "Mona Lisa"
    Confirm that you have set the Git username correctly:
    $ git config --global user.name
    > Mona Lisa

**Step 5:** Save your primary address
Go to github.com
Click on your account 
Click email on LHS
Click save next to your Primary Email Address

**Step 6:** Confirm your github username
$ git config user.email _"email@example.com"_
Confirm that you have set the email address correctly in Git:
$ git config user.email
_email@example.com_

**Step 7**
Download the Marvel Project with the following command in VS Code: 
https://github.com/MrMusovic/PokemonProject.git

Enjoy the project and let's get it.

**Comment by slytherin-boi** [comment]
noot noot

**Comment by tvdk-sudoku** [comment]
Hi
